name: omar_system
description: omar_system App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

#--------  Local DataBase Dependencies  -------------#

  hive: ^2.2.3
  hive_flutter: ^1.1.0

#--------  State Management Dependencies  -------------#

  provider: ^6.0.5
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
#  provider: ^6.0.3

#--------  Icons Dependencies  -------------#

  cupertino_icons: ^1.0.5
  iconsax: ^0.0.8
#  font_awesome_flutter: ^10.1.0

#--------  Network Dependencies  -------------#

  http: ^0.13.5
  dio: ^4.0.6
  cached_network_image: ^3.2.3
  flutter_widget_from_html_core: ^0.9.0+2
  data_connection_checker_tv: ^0.3.5-nullsafety
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.1.5

#--------  Styling Dependencies  -------------#

  carousel_slider: ^4.1.1
  flutter_onboarding_slider: ^1.0.7
  google_nav_bar: ^5.0.6
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.7
  double_back_to_close: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_rating_bar: ^4.0.1
  auto_size_text: ^3.0.0
  accordion: ^2.5.1
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.2
  font_awesome_flutter: ^10.2.1
  convex_bottom_bar: ^3.1.0+1
  horizontal_data_table: ^4.1.3
  search_page: ^2.2.0
  sticky_headers: ^0.3.0+2
#--------  App Tutorial Dependencies  -------------#


#  flutter_sliding_tutorial: ^1.1.3+3
#  tutorial_coach_mark: ^1.2.4


#--------  App Secure Dependencies  -------------#

#  secure_application: ^3.8.0
#  keep_screen_on: ^2.0.0

#--------  Helper Dependencies  -------------#

  flutter_svg: ^1.1.3
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  keyboard_dismisser: ^3.0.0
  intl_phone_number_input:
    git:
      url: https://github.com/AbdOoSaed/intl_phone_number_input
  jiffy: ^5.0.0
  share_plus: ^4.0.10+1
  device_info_plus: ^4.1.0

  call_log: ^4.0.0
  workmanager: ^0.5.1

#  flutter_phoenix: ^1.0.0
#  intl_phone_number_input: ^0.7.0+2
#  restart_app: ^1.1.0
#  flutter_phoenix: ^1.0.0
#  firebase_messaging: ^12.0.2
#  flutter_background: ^1.1.0


#--------  Video Player Dependencies  -------------#


  pod_player: ^0.1.0
  calendar_date_picker2: ^0.5.2
  fluttertoast: ^8.2.2
#  vimeo_video_player: ^0.0.4
#  youtube_player_iframe: ^3.0.2
#  better_player: ^0.0.83
#  chewie: ^1.3.4
#  flick_video_player: ^0.5.0

#--------  Zoom Dependencies  -------------#

#  flutter_zoom_sdk: ^1.1.0+4




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/
    - assets/fonts/


  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
    - family: Janna
      fonts:
        - asset: assets/fonts/janna/JannaLT-Regular.ttf
        - asset: assets/fonts/janna/JannaLT-Bold.ttf
          weight: 700
    - family: Jooza
      fonts:
        - asset: assets/fonts/jooza/flat-jooza-regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
          weight: 900



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-icone.png"


#  flutter pub run flutter_launcher_icons:main

#  flutter pub run flutter_native_splash:create


flutter_native_splash:
  color: "#FFFFFF"

  image: assets/logo2.png

  #color_dark: "#042a49"
  #image_dark: assets/splash-invert.png

  #android: false
  #ios: false
# https://omar.training/
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center

  # To hide the notification bar on Android, use the android_fullscreen parameter.  Defaults to
  # false.
  android_fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
